### ISSUE TITLE
License plate

### ISSUE THREAD

**Issue by BlinbD** [PineappleOnMyPizza/maji-gasdelivery#2]
There is a current issue where because each truck spawns with the same license plate, if more than one person does the job they will share glovebox / trunk items... Randomize the plates at spawn?

**Suggestion below, not an issue:**
Also, would love to see a time check built into this to avoid players grinding it, or perhaps a police check for those servers that have commercial vehicle enforcement RP.

**Comment by MajiSP** [comment]
This has been fixed 💯
